server:

  port: 9192
spring:
  application:
    name: order-service
    jpa:
      defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

application:
  name: ORDER-SERVICE

  logging:
    file: /Users/apple/Documents/microservice/microservice.log







